apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "govault-autounseal.fullname" . }}
  labels:
    {{- include "govault-autounseal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "govault-autounseal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "govault-autounseal.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "govault-autounseal.serviceAccountName" . }}
      {{- end }}
      containers:
      - name: govault-autounseal
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["start", "--config", "/config/config.yaml"]
        ports:
        - name: http
          containerPort: {{ .Values.config.http_server.port }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "govault-autounseal.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}