{{- if and .Values.rbac.create (eq .Values.mode "kube") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "govault-autounseal.fullname" . }}
  namespace: {{ .Values.kubeConfig.vault_namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/proxy", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "govault-autounseal.fullname" . }}
  namespace: {{ .Values.kubeConfig.vault_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "govault-autounseal.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "govault-autounseal.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}