apiVersion: v2
name: govault-autounseal
description: A Helm chart for govault-autounseal Go application that automatically unseals HashiCorp Vault
type: application
version: 0.1.0
appVersion: "1.0.0"
